### ISSUE TITLE
Issue with dplyr 1.1.0

### ISSUE THREAD

**Issue by PMassicotte** [MilesMcBain/breakerofchains#21] opened 2023-01-30 22:30 UTC
See changes in `lead()`/`lag()` functions in the newest release of `dplyr`: https://github.com/tidyverse/dplyr/blob/main/NEWS.md

> lag() and lead() now cast default to the type of x, rather than taking the common type. This ensures that these functions are type stable on x (#6330).

This is causing this error:

```r
r$> rlang::last_error()
<error/vctrs_error_cast_lossy>
Error in `dplyr::lead()`:
! Can't convert from `default` <double> to `x` <integer> due to loss of precision.
```

At this line:

https://github.com/MilesMcBain/breakerofchains/blob/5c8d0e176ed2188a14f930a31640bc5465bfb890/R/polyfill_base_pipe.R#L19

I think a fix would be simply replacing `dplyr::lead(greater_than, default = FALSE)` by `dplyr::lead(greater_than, default = 0)`.

Thank you for the great package, very useful to me.

**Comment by PMassicotte** [comment] 2023-01-31 13:47
I think #18 would fix the issue as well.

**Comment by MilesMcBain** [comment] 2023-01-31 22:57
Thanks for this!

I already addressed what was proposed in #18 in a different way. This is coming from a different line to the one that was changed.

**Comment by MilesMcBain** [comment] 2023-01-31 23:04
Hmm, Are you sure the line you've highlighted is the one?

It seems that at that line it should only be possible for greater_than to be logical on account of:

```
 greater_than <- source_tokens$value == ">"
```

The error should be complaining about logical type, but it's talking about int / double which sounds suspiciously like the error I fixed with: https://github.com/MilesMcBain/breakerofchains/commit/039b4b537d7b1785994fc1d06a7d2f56a57d0871

Can you check `packageVersion("breakerofchains") == "0.3.2"`

**Comment by PMassicotte** [comment] 2023-02-01 08:56
```r
r$> packageVersion("breakerofchains") == "0.3.2"
[1] TRUE
```

I have forked and fixed it on my side: 

https://github.com/PMassicotte/breakerofchains/blob/665d38135e31dfd176f2b3c280c2e795edacb1b0/R/polyfill_base_pipe.R#L18-L24

It is now working fine on my side.

**Comment by MilesMcBain** [comment] 2023-02-01 09:58
I can't reproduce the issue with CRAN `{dplyr}` 1.1.0.

What I think has happened here is that you were on a prior version (< 0.3.2) when you made this bug report, and after you forked you got 0.3.2 and the change that fixed this error. The change you made has not affected anything.

I'm fairly confident about this because I don't believe it's possible for this error:

```
! Can't convert from `default` <double> to `x` <integer> due to loss of precision.
```
to have come from the lines you changed, since the type of those vectors must be logical, and this error is about a type conflict between double and integer. 

The error actually came from here, where on your older version you had `Inf` instead of `.Machine$integer.max`: https://github.com/PMassicotte/breakerofchains/blob/665d38135e31dfd176f2b3c280c2e795edacb1b0/R/polyfill_base_pipe.R#L16

**Closed as completed by MilesMcBain** 2023-02-01 09:58 UTC
